// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: grpc/player.proto

package playerpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetPlayerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPlayerRequest) Reset() {
	*x = GetPlayerRequest{}
	mi := &file_grpc_player_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPlayerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPlayerRequest) ProtoMessage() {}

func (x *GetPlayerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_player_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPlayerRequest.ProtoReflect.Descriptor instead.
func (*GetPlayerRequest) Descriptor() ([]byte, []int) {
	return file_grpc_player_proto_rawDescGZIP(), []int{0}
}

func (x *GetPlayerRequest) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

type GetPlayerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPlayerResponse) Reset() {
	*x = GetPlayerResponse{}
	mi := &file_grpc_player_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPlayerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPlayerResponse) ProtoMessage() {}

func (x *GetPlayerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_player_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPlayerResponse.ProtoReflect.Descriptor instead.
func (*GetPlayerResponse) Descriptor() ([]byte, []int) {
	return file_grpc_player_proto_rawDescGZIP(), []int{1}
}

func (x *GetPlayerResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetPlayerResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_grpc_player_proto protoreflect.FileDescriptor

const file_grpc_player_proto_rawDesc = "" +
	"\n" +
	"\x11grpc/player.proto\x12\x06player\"/\n" +
	"\x10GetPlayerRequest\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\"7\n" +
	"\x11GetPlayerResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name2Q\n" +
	"\rPlayerService\x12@\n" +
	"\tGetPlayer\x12\x18.player.GetPlayerRequest\x1a\x19.player.GetPlayerResponseB\x1bZ\x19grpc/pb/playerpb;playerpbb\x06proto3"

var (
	file_grpc_player_proto_rawDescOnce sync.Once
	file_grpc_player_proto_rawDescData []byte
)

func file_grpc_player_proto_rawDescGZIP() []byte {
	file_grpc_player_proto_rawDescOnce.Do(func() {
		file_grpc_player_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_grpc_player_proto_rawDesc), len(file_grpc_player_proto_rawDesc)))
	})
	return file_grpc_player_proto_rawDescData
}

var file_grpc_player_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_grpc_player_proto_goTypes = []any{
	(*GetPlayerRequest)(nil),  // 0: player.GetPlayerRequest
	(*GetPlayerResponse)(nil), // 1: player.GetPlayerResponse
}
var file_grpc_player_proto_depIdxs = []int32{
	0, // 0: player.PlayerService.GetPlayer:input_type -> player.GetPlayerRequest
	1, // 1: player.PlayerService.GetPlayer:output_type -> player.GetPlayerResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_grpc_player_proto_init() }
func file_grpc_player_proto_init() {
	if File_grpc_player_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_grpc_player_proto_rawDesc), len(file_grpc_player_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_grpc_player_proto_goTypes,
		DependencyIndexes: file_grpc_player_proto_depIdxs,
		MessageInfos:      file_grpc_player_proto_msgTypes,
	}.Build()
	File_grpc_player_proto = out.File
	file_grpc_player_proto_goTypes = nil
	file_grpc_player_proto_depIdxs = nil
}
