include:
  - ../infra/development/docker-compose.yaml

services: # Burası eksikti, tüm servisler bunun altında olmalı
  api: # Servis adı kısa ve öz olabilir
    image: berkerturan/tennis-league-main-api:latest
    pull_policy: always
    container_name: tennis-league-api
    ports:
      - "8500:8500"
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=tennisleague
      - POSTGRES_PASSWORD=tennisleague
      - POSTGRES_DB=tennisleague
      - POSTGRES_SSLMODE=disable
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=
    networks:
      - tennis-net
    depends_on:
      postgres:
        condition: service_healthy
      schema-initializer:
        condition: service_completed_successfully
      redis:
        condition: service_healthy

  user-api: # Servis adı kısa ve öz olabilir
    image: berkerturan/tennis-league-user-api:latest
    pull_policy: always
    container_name: user-api
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=tennisleague
      - POSTGRES_PASSWORD=tennisleague
      - POSTGRES_DB=tennisleague
      - POSTGRES_SSLMODE=disable
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=
    networks:
      - tennis-net
    depends_on:
      postgres:
        condition: service_healthy
      schema-initializer:
        condition: service_completed_successfully
      redis:
        condition: service_healthy

  main-publisher:
    image: berkerturan/tennis-league-main-publisher:latest
    pull_policy: always
    container_name: main-publisher
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=tennisleague
      - POSTGRES_PASSWORD=tennisleague
      - POSTGRES_DB=tennisleague
      - POSTGRES_SSLMODE=disable
      - RABBIT_USER=admin
      - RABBIT_PASSWORD=admin123
      - RABBIT_HOST=rabbitmq
      - RABBIT_PORT=5672
      - RABBIT_VHOST=/
    networks:
      - tennis-net
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_started
      schema-initializer:
        condition: service_completed_successfully

  main-consumer:
    image: berkerturan/tennis-league-main-consumer:latest
    pull_policy: always
    container_name: main-consumer
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=tennisleague
      - POSTGRES_PASSWORD=tennisleague
      - POSTGRES_DB=tennisleague
      - POSTGRES_SSLMODE=disable
      - RABBIT_USER=admin
      - RABBIT_PASSWORD=admin123
      - RABBIT_HOST=rabbitmq
      - RABBIT_PORT=5672
      - RABBIT_VHOST=/
    networks:
      - tennis-net
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_started
      schema-initializer:
        condition: service_completed_successfully

  user-consumer:
    image: berkerturan/tennis-league-user-consumer:latest
    pull_policy: always
    container_name: user-consumer
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=tennisleague
      - POSTGRES_PASSWORD=tennisleague
      - POSTGRES_DB=tennisleague
      - POSTGRES_SSLMODE=disable
      - RABBIT_USER=admin
      - RABBIT_PASSWORD=admin123
      - RABBIT_HOST=rabbitmq
      - RABBIT_PORT=5672
      - RABBIT_VHOST=/
    networks:
      - tennis-net
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_started
      schema-initializer:
        condition: service_completed_successfully

  frontend:
    image: berkerturan/tennis-league-ui-docker:latest
    pull_policy: always
    container_name: tennis-league-ui
    ports:
      - "3000:80"
    networks:
      - tennis-net
    depends_on:
      - api # Yukarıdaki servis adı 'api' olduğu için burayı güncelledim

networks:
  tennis-net:
    driver: bridge